# Generated by Django 2.2.6 on 2019-11-15 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0006_mate'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='mates',
            field=models.ManyToManyField(to='p_library.Mate'),
        ),
    ]
