# Generated by Django 2.2.6 on 2019-11-15 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0007_book_mates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='mates',
            field=models.ManyToManyField(blank=True, to='p_library.Mate'),
        ),
    ]
